Fixes

diff --git a/libzeropool-rs-wasm/scripts/build b/libzeropool-rs-wasm/scripts/build
--- a/libzeropool-rs-wasm/scripts/build
+++ b/libzeropool-rs-wasm/scripts/build
@@ -2,6 +2,12 @@
 
 PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
 
+if ! command -v jq &> /dev/null
+then
+    echo "jq is required to run this script: https://stedolan.github.io/jq/"
+    exit
+fi
+
 function build () {
   wasm-pack build --release --target web -d $1 -- --features $2
   # Optimize the binary, since wasm-pack refuses to see wasm-opt
@@ -19,3 +25,6 @@ function build () {
 
 build web "web"
 build web-mt "web","multicore"
+
+jq '.files |= . + ["snippets"]' $PARENT_DIR/web-mt/package.json > $PARENT_DIR/web-mt/tmp.json \
+  && mv $PARENT_DIR/web-mt/tmp.json $PARENT_DIR/web-mt/package.json
